apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cert-set-default-namespace
patch: |-
  - op: replace
    path: /metadata/namespace
    value: default
target:
  group: cert-manager.io
  version: v1
  kind: Certificate
  name: python-dsa-tls-cert
