apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: artifact-registry-writer
spec:
  member: serviceAccount:kame-house-oidc@kame-457417.iam.gserviceaccount.com
  role: roles/artifactregistry.writer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: kame-457417
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: container-admin
spec:
  member: serviceAccount:kame-house-oidc@kame-457417.iam.gserviceaccount.com
  role: roles/container.admin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: kame-457417
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: dns-admin
spec:
  member: serviceAccount:kame-house-oidc@kame-457417.iam.gserviceaccount.com
  role: roles/dns.admin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: kame-457417
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: workload-identity-user
spec:
  member: principalSet://iam.googleapis.com/projects/316518955652/locations/global/workloadIdentityPools/github-pool/attribute.repository/ianlintner/python_dsa
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    external: kame-house-oidc@kame-457417.iam.gserviceaccount.com
---
apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
kind: ArtifactRegistryRepository
metadata:
  name: python-dsa
spec:
  location: us-central1
  format: DOCKER
  description: Docker repository for python-dsa project
