name: LeetCode Top 100 Documentation Audit

on:
  push:
    branches: [main]
    paths:
      - 'src/interview_workbook/leetcode/**'
      - 'docs/NEETCODE_TOP100.md'
  pull_request:
    branches: [main]
    paths:
      - 'src/interview_workbook/leetcode/**'
      - 'docs/NEETCODE_TOP100.md'

jobs:
  audit-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run LeetCode audit
      run: |
        python scripts/leetcode_manager.py audit

    - name: Check if docs are up to date
      run: |
        # Generate fresh docs (continue on import errors for now)
        python scripts/leetcode_manager.py update-docs || echo "⚠️ Some import errors occurred during doc generation"

        # Check if git shows any changes
        if ! git diff --quiet docs/NEETCODE_TOP100.md; then
          echo "⚠️ Documentation is out of date! Auto-updating..."
          echo "Changes detected:"
          git diff docs/NEETCODE_TOP100.md

          # Auto-commit the documentation update
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/NEETCODE_TOP100.md
          git commit -m "chore: auto-update LeetCode documentation" || echo "No changes to commit"

          echo "✅ Documentation updated automatically"
        else
          echo "✅ Documentation is up to date!"
        fi
